import googlePlacesDataJson from "./google-places-data.json";

export type HalalStatus = "zabiha" | "halal" | "select-items";

export type Region =
  | "Chicago"
  | "North Suburbs"
  | "Northwest Suburbs"
  | "West Suburbs"
  | "Southwest Suburbs"
  | "South Suburbs";

export interface Restaurant {
  id: string;
  name: string;
  neighborhood: string;
  region: Region;
  address: string;
  cuisine: string;
  halalStatus: HalalStatus;
  rating: number;
  reviewCount: number;
  priceLevel: "$" | "$$" | "$$$";
  image: string;
  lat: number;
  lng: number;
  description: string;
  /** Present when verified against Google Places (see scripts/enrich-places.mjs). */
  googleMapsUri?: string;
  websiteUri?: string;
  openingHours?: string[];
  /**
   * Path to a photographed halal/Zabiha certification document, e.g.
   * "/certificates/al-bawadi-grill.jpg". Drop the image in
   * public/certificates/ named after the restaurant's id and set this
   * field to wire it up — left unset until a certificate is collected.
   */
  certificateImage?: string;
  /** Broad category derived from `cuisine`, used by the cuisine filter. */
  cuisineCategory: string;
}

/** Broad cuisine bucket used by the cuisine filter, derived from the free-text `cuisine` field. */
function categorizeCuisine(cuisine: string): string {
  const c = cuisine.toLowerCase();
  if (c.includes("indo-chinese") || c.includes("chinese")) return "Chinese";
  if (
    c.includes("nihari") ||
    c.includes("pakistani") ||
    c.includes("indian") ||
    c.includes("bangladeshi") ||
    c.includes("hyderabadi") ||
    c.includes("biryani") ||
    c.includes("chai")
  )
    return "South Asian";
  if (c.includes("nashville") || c.includes("hot chicken") || c.includes("peri peri") || c.includes("fried chicken"))
    return "Chicken";
  if (c.includes("smoked bbq") || c.includes("b.b.q") || c.includes(" bbq")) return "BBQ";
  if (c.includes("pizza")) return "Pizza";
  if (c.includes("burger") || c.includes("wings") || c.includes("comfort food")) return "American";
  if (c.includes("bakery") || c.includes("cafe")) return "Bakery / Cafe";
  if (c.includes("uzbek") || c.includes("afghan") || c.includes("uyghur") || c.includes("central asian"))
    return "Central Asian";
  if (c.includes("mediterranean") && !c.includes("middle eastern")) return "Mediterranean";
  if (
    c.includes("middle eastern") ||
    c.includes("falafel") ||
    c.includes("shawarma") ||
    c.includes("egyptian") ||
    c.includes("palestinian") ||
    c.includes("halal cart")
  )
    return "Middle Eastern";
  if (c.includes("african")) return "African";
  if (c.includes("halal grill") || c.includes("halal fast food") || c.includes("ny-style") || c.includes("ny halal"))
    return "Halal Grill";
  return "Other";
}

/**
 * Seed dataset compiled from public halal-directory sources (Zabihah listings,
 * local halal-food roundups, restaurant sites) for the initial Chicagoland
 * launch map. Addresses/coordinates for the Devon Ave and Bridgeview clusters
 * are well corroborated; several suburban entries rest on a single directory
 * snapshot and should be re-verified (hours, certification, still open) by
 * an editorial/data pipeline before being treated as authoritative.
 */
const baseRestaurants: Omit<Restaurant, "cuisineCategory">[] = [
  {
    id: "karachi-chaat-house",
    name: "Karachi Chaat House",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2301 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani",
    halalStatus: "zabiha",
    rating: 4.6,
    reviewCount: 812,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6889,
    description: "Devon Ave institution serving 100% Zabiha bun kabab, biryani, and nihari late into the night.",
  },
  {
    id: "usmania-fine-dining",
    name: "Usmania Fine Dining",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2244 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani / Indian",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 640,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6880,
    description: "Established South Asian dining room on Devon Ave known for karahi and Zabiha meats.",
  },
  {
    id: "spinzer-restaurant",
    name: "Spinzer Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "Devon Ave near Western Ave, Chicago, IL",
    cuisine: "Pakistani Street Food",
    halalStatus: "zabiha",
    rating: 4.5,
    reviewCount: 410,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6903,
    description: "Zabiha halal Pakistani street food — chaat, biryani, and karahi — since 2008.",
  },
  {
    id: "ghareeb-nawaz",
    name: "Ghareeb Nawaz Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2032 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 980,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6870,
    description: "The flagship Devon Ave location, open nearly 24/7 — a staple for late-night students and taxi drivers.",
  },
  {
    id: "new-naan-on-devon",
    name: "New Naan on Devon",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2241 W Devon Ave, Chicago, IL 60659",
    cuisine: "Hyderabadi / Middle Eastern Grill",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6878,
    description: "Hyderabadi biryani and Middle Eastern grill items on the Devon corridor.",
  },
  {
    id: "sultans-market",
    name: "Sultan's Market",
    neighborhood: "Wicker Park",
    region: "Chicago",
    address: "Milwaukee Ave & North Ave, Chicago, IL",
    cuisine: "Mediterranean / Middle Eastern",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 1200,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9100,
    lng: -87.6773,
    description: "Decades-old Wicker Park halal falafel and shawarma counter.",
  },
  {
    id: "semiramis",
    name: "Semiramis",
    neighborhood: "Lincoln Square",
    region: "Chicago",
    address: "Lincoln Ave, Chicago, IL",
    cuisine: "Middle Eastern Bakery / Deli",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 350,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9686,
    lng: -87.6890,
    description: "Long-standing halal Middle Eastern bakery and deli known for shawarma and manakeesh.",
  },
  {
    id: "kabul-house",
    name: "Kabul House",
    neighborhood: "Evanston",
    region: "North Suburbs",
    address: "Davis St, Evanston, IL",
    cuisine: "Afghan",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 540,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0451,
    lng: -87.6877,
    description: "Well-regarded Afghan restaurant known for mantu and kabobs.",
  },
  {
    id: "jarasa-kabob",
    name: "Jarasa Kabob",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Oakton St area, Skokie, IL",
    cuisine: "Middle Eastern / Mediterranean",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0324,
    lng: -87.7412,
    description: "Popular kabob and shawarma spot serving Skokie, Evanston, and Lincolnwood.",
  },
  {
    id: "sheikhs-n-burgers",
    name: "Sheikhs N Burgers",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "American / Burgers",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 190,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.7473,
    description: "Halal burger concept popular with the North Shore Muslim community.",
  },
  {
    id: "afghan-kabob-skokie",
    name: "Afghan Kabob",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Dempster St, Skokie, IL",
    cuisine: "Afghan",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0392,
    lng: -87.7515,
    description: "Dempster St Afghan spot known for mantu dumplings and traditional kabobs.",
  },
  {
    id: "byrds-hot-chicken",
    name: "Byrd's Hot Chicken",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "American / Fried Chicken",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 150,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0389,
    lng: -87.7448,
    description: "Nashville-style hot chicken with a halal Skokie location.",
  },
  {
    id: "barakat-restaurant",
    name: "Barakat Restaurant",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "Schaumburg, IL",
    cuisine: "Middle Eastern / Palestinian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 410,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0333,
    lng: -88.0834,
    description: "Regional halal Mediterranean/Palestinian restaurant with multiple NW suburb locations.",
  },
  {
    id: "ali-baba-kabab",
    name: "Ali Baba Kabab",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "Roselle Rd, Schaumburg, IL",
    cuisine: "Middle Eastern",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1633945274309-2c3b3d9be1e5?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0459,
    lng: -88.0784,
    description: "Roselle Rd kabob and grill spot popular in Schaumburg's halal food scene.",
  },
  {
    id: "curry-naanstop",
    name: "Curry NaanStop",
    neighborhood: "Mount Prospect",
    region: "Northwest Suburbs",
    address: "338 E Rand Rd, Mount Prospect, IL 60004",
    cuisine: "Indian / Pakistani",
    halalStatus: "halal",
    rating: 4.8,
    reviewCount: 520,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0928,
    lng: -87.9364,
    description: "Halal-certified Indian restaurant on the Rand Rd corridor.",
  },
  {
    id: "uyghur-lagman-house",
    name: "Uyghur Lagman House",
    neighborhood: "Arlington Heights",
    region: "Northwest Suburbs",
    address: "Arlington Heights, IL",
    cuisine: "Uyghur / Central Asian",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 180,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0884,
    lng: -87.9806,
    description: "Rare Uyghur hand-pulled noodle house serving halal Central Asian cuisine.",
  },
  {
    id: "mazmez-grill",
    name: "MazMez Middle Eastern Grill",
    neighborhood: "Elk Grove Village",
    region: "Northwest Suburbs",
    address: "Elk Grove Village, IL",
    cuisine: "Middle Eastern",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 140,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0034,
    lng: -87.9773,
    description: "Middle Eastern grill offering shawarma and kabobs in Elk Grove Village.",
  },
  {
    id: "a-thousand-tales",
    name: "A Thousand Tales",
    neighborhood: "Des Plaines",
    region: "Northwest Suburbs",
    address: "Des Plaines, IL",
    cuisine: "Middle Eastern Bakery / Cafe",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 210,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.8834,
    description: "Middle Eastern bakery-cafe concept with locations across the NW suburbs.",
  },
  {
    id: "jk-kabab",
    name: "JK Kabab",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "572 Weston Ridge Dr, Naperville, IL",
    cuisine: "Indian / Pakistani",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 330,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7508,
    lng: -88.1535,
    description: "Naperville halal grill known for kabobs and Desi-style curries.",
  },
  {
    id: "habibi-shawarma",
    name: "Habibi Shawarma",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "Naperville, IL",
    cuisine: "Middle Eastern / Shawarma",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 290,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7858,
    lng: -88.1470,
    description: "Popular Naperville shawarma and falafel counter.",
  },
  {
    id: "halal-express-villa-park",
    name: "Halal Express",
    neighborhood: "Villa Park",
    region: "West Suburbs",
    address: "17W731 Roosevelt Rd, Villa Park, IL",
    cuisine: "American / Halal Fast Food",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 175,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8734,
    lng: -87.9989,
    description: "Roosevelt Rd quick-service halal spot serving gyro and chicken-over-rice plates.",
  },
  {
    id: "biryani-pointe",
    name: "Biryani Pointe",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "40 W Roosevelt Rd, Lombard, IL",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 240,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -88.0084,
    description: "Biryani and kabob restaurant on the Roosevelt Rd corridor in Lombard.",
  },
  {
    id: "tapri",
    name: "Tapri",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "Naperville, IL",
    cuisine: "Indian Street Food / Chai",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 160,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7796,
    lng: -88.1616,
    description: "Indian street-food and chai cafe; select menu items are prepared halal.",
  },
  {
    id: "al-bawadi-grill",
    name: "Al Bawadi Grill",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "7216 W 87th St, Bridgeview, IL 60455",
    cuisine: "Palestinian / Middle Eastern",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 1500,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7361,
    lng: -87.8103,
    description: "Fully halal Palestinian restaurant famous for mansaf and musakhan.",
  },
  {
    id: "nariman-restaurant",
    name: "Nariman Restaurant",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "8312 S Harlem Ave, Bridgeview, IL",
    cuisine: "Middle Eastern",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 280,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7412,
    lng: -87.8067,
    description: "Harlem Ave Middle Eastern restaurant serving Zabiha halal fare.",
  },
  {
    id: "krave-restaurant",
    name: "Krave Restaurant",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "Bridgeview, IL",
    cuisine: "American / Middle Eastern Fusion",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 340,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7500,
    lng: -87.8103,
    description: "100% halal menu; open 24 hours Fridays and Saturdays, a popular late-night spot.",
  },
  {
    id: "mdakhan",
    name: "M'daKhan",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "9115 S Harlem Ave, Bridgeview, IL 60455",
    cuisine: "Middle Eastern / Smoked BBQ",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 210,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1633945274309-2c3b3d9be1e5?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7450,
    lng: -87.8050,
    description: "Registered under the Illinois Halal Registration Act with hand-slaughtered meats — wood-smoked BBQ and Middle Eastern flavors.",
  },
  {
    id: "holy-buckets",
    name: "Holy Buckets Halal Chicken & Pizza",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "7331 W 87th St, Bridgeview, IL",
    cuisine: "American / Fried Chicken",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7360,
    lng: -87.8129,
    description: "Halal fried chicken and pizza serving Bridgeview, Oak Lawn, and Justice.",
  },
  {
    id: "alasala",
    name: "Alasala",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "Bridgeview, IL",
    cuisine: "Mediterranean / Palestinian",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 190,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7480,
    lng: -87.8090,
    description: "Muslim-owned Mediterranean/Palestinian restaurant in Bridgeview.",
  },
  {
    id: "semsem-mediterranean",
    name: "SemSem Mediterranean",
    neighborhood: "Orland Park",
    region: "South Suburbs",
    address: "Orland Park, IL",
    cuisine: "Mediterranean",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 300,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.6303,
    lng: -87.8531,
    description: "Orland Park Mediterranean grill offering halal shawarma, platters, and catering.",
  },
  {
    id: "brooklyn-halal",
    name: "Brooklyn Halal Grilled Chicken & Pizza",
    neighborhood: "Tinley Park",
    region: "South Suburbs",
    address: "Tinley Park, IL",
    cuisine: "American / Fried Chicken & Pizza",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.5735,
    lng: -87.7929,
    description: "Halal fried chicken and pizza chain with a South Suburbs footprint.",
  },
  {
    id: "nazs-halal-food",
    name: "Naz's Halal Food",
    neighborhood: "Tinley Park",
    region: "South Suburbs",
    address: "Tinley Park, IL",
    cuisine: "Halal Grill",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 180,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.5764,
    lng: -87.7847,
    description: "Top-rated Tinley Park halal grill in local roundups.",
  },
  {
    id: "hakuna-matata",
    name: "Hakuna Matata",
    neighborhood: "Orland Park",
    region: "South Suburbs",
    address: "Orland Park, IL",
    cuisine: "African / Halal Grill",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 130,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.6112,
    lng: -87.8536,
    description: "African-influenced halal grill serving the Orland Park / Tinley Park area.",
  },
  {
    id: "wow-halal-grill",
    name: "Wow Halal Grill & Pizza",
    neighborhood: "Tinley Park",
    region: "South Suburbs",
    address: "Tinley Park, IL",
    cuisine: "American / Halal Fast Food",
    halalStatus: "halal",
    rating: 4.0,
    reviewCount: 150,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.5798,
    lng: -87.7900,
    description: "Casual halal grill-and-pizza spot serving the Tinley Park area.",
  },
  {
    id: "usmania-chinese",
    name: "Usmania Chinese Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2253 W Devon Ave, Chicago, IL 60659",
    cuisine: "Indo-Chinese",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6892,
    description: "Traditional halal Indo-Chinese menu in a casual, bright Devon Ave storefront.",
  },
  {
    id: "faiza-chicago",
    name: "Faiza Chicago",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "3315 W Bryn Mawr Ave, Chicago, IL 60659",
    cuisine: "Pakistani / Indian",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 250,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9832,
    lng: -87.7130,
    description: "A well-regarded Zabiha halal spot on Chicago's North Side.",
  },
  {
    id: "euroasia-restaurant",
    name: "EuroAsia Restaurant",
    neighborhood: "Near North Side",
    region: "Chicago",
    address: "351 W Oak St, Chicago, IL 60610",
    cuisine: "Uzbek / Central Asian",
    halalStatus: "zabiha",
    rating: 4.5,
    reviewCount: 400,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9004,
    lng: -87.6376,
    description: "Top-rated Zabiha dining near downtown Chicago, open daily with a dedicated halal menu.",
  },
  {
    id: "ruman-chai-shai",
    name: "Ruman Chai Shai & Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "6348 N Artesian Ave, Chicago, IL 60659",
    cuisine: "Pakistani Tea House / Chai",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 150,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9962,
    lng: -87.7020,
    description: "Explicitly Zabiha halal, known for late-night tea and traditional snacks.",
  },
  {
    id: "chayhana",
    name: "Chayhana",
    neighborhood: "North Center",
    region: "Chicago",
    address: "1812 W Irving Park Rd, Chicago, IL 60613",
    cuisine: "Central Asian / Uzbek",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 350,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9541,
    lng: -87.6739,
    description: "Central Asian tea-house cuisine with early morning to late-night hours.",
  },
  {
    id: "halal-burger-lombard",
    name: "The Halal Burger",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "916 E Roosevelt Rd, Lombard, IL 60148",
    cuisine: "American / Burgers",
    halalStatus: "zabiha",
    rating: 4.5,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -88.0056,
    description: "HMS-registered smash burgers with extended late-night hours on weekends.",
  },
  {
    id: "taste-on-fire",
    name: "Taste On Fire",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "4209 Main St, Skokie, IL 60076",
    cuisine: "American / Comfort Food",
    halalStatus: "zabiha",
    rating: 4.6,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0389,
    lng: -87.7473,
    description: "Highly-rated fast-casual spot serving a variety of Zabiha comfort foods.",
  },
  {
    id: "halal-burger-original",
    name: "The Halal Burger",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "6234 N California Ave, Chicago, IL 60659",
    cuisine: "American / Burgers",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 400,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6996,
    description: "HMS-registered original location — wings, Italian beef, and hot dogs in no-frills digs near Devon Ave.",
  },
  {
    id: "halal-burger-skokie",
    name: "The Halal Burger",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "3457 Dempster St, Skokie, IL 60076",
    cuisine: "American / Burgers",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 200,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0392,
    lng: -87.7515,
    description: "Same HMS registry standard as the original Chicago location, with a Chicago-style menu.",
  },
  {
    id: "halal-pizza-point",
    name: "Halal Pizza Point",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "5230 Dempster St, Skokie, IL 60077",
    cuisine: "Pizza",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 180,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0392,
    lng: -87.7590,
    description: "Dedicated to halal-certified pizzas and sides — a popular family-friendly option.",
  },
  {
    id: "slaw-burger-schaumburg",
    name: "Slaw Burger",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "1332 N Roselle Rd, Schaumburg, IL 60195",
    cuisine: "American / Burgers",
    halalStatus: "zabiha",
    rating: 4.5,
    reviewCount: 190,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0459,
    lng: -88.0784,
    description: "HMS-registered smash burgers topped with house slaw, serving the northwest suburbs.",
  },
  {
    id: "shahs-halal-food",
    name: "Shah's Halal Food",
    neighborhood: "Chicago Ridge",
    region: "Southwest Suburbs",
    address: "9920 S Ridgeland Ave, Chicago Ridge, IL 60415",
    cuisine: "American / NY-Style Halal Cart",
    halalStatus: "zabiha",
    rating: 4.6,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7078,
    lng: -87.7889,
    description: "100% certified halal New York-style street food — chicken, lamb, and falafel platters over rice.",
  },
  {
    id: "salt-burgers-fries",
    name: "SALT burgers + fries",
    neighborhood: "Wicker Park",
    region: "Chicago",
    address: "1920 W North Ave, Chicago, IL 60622",
    cuisine: "American / Burgers",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 500,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9101,
    lng: -87.6773,
    description: "Trendy Wicker Park smash burger spot; halal certificates are posted on premises.",
  },
  {
    id: "ghareeb-nawaz-lombard",
    name: "Ghareeb Nawaz",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "833 E Roosevelt Rd, Lombard, IL 60148",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 400,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -88.0067,
    description: "Bustling iconic halal eatery famous for massive portions at modest prices.",
  },
  {
    id: "ghareeb-nawaz-lincoln-park",
    name: "Ghareeb Nawaz",
    neighborhood: "Lincoln Park",
    region: "Chicago",
    address: "2364 N Lincoln Ave, Chicago, IL 60614",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 350,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9251,
    lng: -87.6539,
    description: "Brings the brand's affordable South Asian menu to the North Side; popular with university students.",
  },
  {
    id: "ghareeb-nawaz-uic",
    name: "Ghareeb Nawaz",
    neighborhood: "Near West Side",
    region: "Chicago",
    address: "807 W Roosevelt Rd, Chicago, IL 60608",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8672,
    lng: -87.6497,
    description: "Positioned for the medical and academic district, with the same hearty budget-friendly menu.",
  },
  {
    id: "ghareeb-nawaz-ohare",
    name: "Ghareeb Nawaz",
    neighborhood: "Des Plaines",
    region: "Northwest Suburbs",
    address: "2685 Mannheim Rd, Des Plaines, IL 60018",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 280,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9847,
    lng: -87.8636,
    description: "24-hour service near O'Hare — reliable halal food at any hour for travelers.",
  },
  {
    id: "tandoor-char-house-lincoln-park",
    name: "Tandoor Char House",
    neighborhood: "Lincoln Park",
    region: "Chicago",
    address: "2652 N Halsted St, Chicago, IL 60614",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 450,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9284,
    lng: -87.6493,
    description: "Upscale sit-down Pakistani and Indian halal fare in Lincoln Park.",
  },
  {
    id: "tandoor-char-house-ukrainian-village",
    name: "Tandoor Char House",
    neighborhood: "Ukrainian Village",
    region: "Chicago",
    address: "1022 N Western Ave, Chicago, IL 60622",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 300,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9019,
    lng: -87.6868,
    description: "The same beloved fusion menu in a vibrant, intimate Ukrainian Village space.",
  },
  {
    id: "daves-hot-chicken-melrose-park",
    name: "Dave's Hot Chicken",
    neighborhood: "Melrose Park",
    region: "West Suburbs",
    address: "2615 W North Ave, Melrose Park, IL 60160",
    cuisine: "American / Nashville Hot Chicken",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 600,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9081,
    lng: -87.8556,
    description: "Chain-supplied halal chicken; store-level certification clarity can vary. Nashville-style tenders and sliders.",
  },
  {
    id: "daves-hot-chicken-schaumburg",
    name: "Dave's Hot Chicken",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "1330 E Golf Rd, Schaumburg, IL 60173",
    cuisine: "American / Nashville Hot Chicken",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 550,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0447,
    lng: -88.0398,
    description: "Serves the bustling northwest suburban shopping district with spice levels up to \"Reaper.\"",
  },
  {
    id: "daves-hot-chicken-chicago",
    name: "Dave's Hot Chicken",
    neighborhood: "North Center",
    region: "Chicago",
    address: "3643 N Western Ave, Chicago, IL 60618",
    cuisine: "American / Nashville Hot Chicken",
    halalStatus: "select-items",
    rating: 4.4,
    reviewCount: 700,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9469,
    lng: -87.6879,
    description: "A late-night favorite for North Center and Roscoe Village, open until midnight or 1am on weekends.",
  },
  {
    id: "daves-hot-chicken-skokie",
    name: "Dave's Hot Chicken",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "5530 W Touhy Ave, Skokie, IL 60077",
    cuisine: "American / Nashville Hot Chicken",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 480,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0033,
    lng: -87.7854,
    description: "Near Village Crossing shopping center; carries the brand's standard halal-supplied poultry.",
  },
  {
    id: "daves-hot-chicken-arlington-heights",
    name: "Dave's Hot Chicken",
    neighborhood: "Arlington Heights",
    region: "Northwest Suburbs",
    address: "115 W Rand Rd C, Arlington Heights, IL 60004",
    cuisine: "American / Nashville Hot Chicken",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 420,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0908,
    lng: -87.9806,
    description: "Extends the brand's footprint further into the northwest suburbs.",
  },
  {
    id: "naf-naf-rosemont",
    name: "Naf Naf Middle Eastern Grill",
    neighborhood: "Rosemont",
    region: "Northwest Suburbs",
    address: "10433 E Touhy Ave, Rosemont, IL 60018",
    cuisine: "Middle Eastern / Fast Casual",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 350,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9847,
    lng: -87.8629,
    description: "Select proteins like chicken shawarma are sourced halal — quick, customizable pita and rice bowls near the airport.",
  },
  {
    id: "naf-naf-oakbrook-terrace",
    name: "Naf Naf Middle Eastern Grill",
    neighborhood: "Oakbrook Terrace",
    region: "West Suburbs",
    address: "17W746 W 22nd St, Oakbrook Terrace, IL 60181",
    cuisine: "Middle Eastern / Fast Casual",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8514,
    lng: -87.9556,
    description: "Caters to the western suburban corporate and shopping crowd; transparent dietary/allergen guidelines online.",
  },
  {
    id: "naf-naf-loop-wabash",
    name: "Naf Naf Middle Eastern Grill",
    neighborhood: "The Loop",
    region: "Chicago",
    address: "28 S Wabash Ave, Chicago, IL 60603",
    cuisine: "Middle Eastern / Fast Casual",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 400,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8809,
    lng: -87.6255,
    description: "Quick Middle Eastern lunch option in the Loop, known for freshly baked pillowy pitas.",
  },
  {
    id: "naf-naf-loop-washington",
    name: "Naf Naf Middle Eastern Grill",
    neighborhood: "The Loop",
    region: "Chicago",
    address: "309 W Washington St, Chicago, IL 60606",
    cuisine: "Middle Eastern / Fast Casual",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 320,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8834,
    lng: -87.6345,
    description: "Serves the downtown office crowd; famous for crispy falafel and signature sauces.",
  },
  {
    id: "naf-naf-south-loop",
    name: "Naf Naf Middle Eastern Grill",
    neighborhood: "South Loop",
    region: "Chicago",
    address: "1248 S Canal St, Chicago, IL 60607",
    cuisine: "Middle Eastern / Fast Casual",
    halalStatus: "select-items",
    rating: 4.1,
    reviewCount: 280,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8636,
    lng: -87.6394,
    description: "Positioned for the South Loop retail district — a reliable, partially-halal fast-casual option.",
  },
  {
    id: "vascos-peri-peri",
    name: "Vasco's Peri Peri",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "440 E Roosevelt Rd, Lombard, IL 60148",
    cuisine: "Peri Peri Chicken",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -88.0000,
    description: "Zabiha halal peri peri flame-grilled chicken on the Roosevelt Rd corridor.",
  },
  {
    id: "wing-zing",
    name: "Wing Zing",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "821 E Roosevelt Rd, Lombard, IL 60148",
    cuisine: "American / Wings",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -88.0055,
    description: "Zabiha halal wings spot serving the Lombard Roosevelt Rd corridor.",
  },
  {
    id: "fyve-bros",
    name: "FYVE BROS",
    neighborhood: "Glendale Heights",
    region: "West Suburbs",
    address: "1581 Bloomingdale Rd, Glendale Heights, IL 60139",
    cuisine: "Halal Grill",
    halalStatus: "zabiha",
    rating: 4.5,
    reviewCount: 190,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9161,
    lng: -88.0800,
    description: "Zabiha halal grill serving Glendale Heights and the surrounding west suburbs.",
  },
  {
    id: "nazs-halal-food-lombard",
    name: "Naz's Halal Food",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "30 W Roosevelt Rd, Lombard, IL 60148",
    cuisine: "Halal Grill",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 210,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -87.9945,
    description: "Lombard location of the Naz's Halal Food grill concept.",
  },
  {
    id: "nyc-halal-eats",
    name: "NYC Halal Eats",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "52 W Roosevelt Rd, Lombard, IL 60148",
    cuisine: "American / NY Halal Cart",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 170,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -87.9950,
    description: "New York City-style halal cart fare brought to the west suburbs.",
  },
  {
    id: "addah",
    name: "Addah",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "1300 S Main St U, Lombard, IL 60148",
    cuisine: "Bangladeshi / South Asian",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 150,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8483,
    lng: -88.0084,
    description: "Bangladeshi and South Asian halal fare in a sit-down setting.",
  },
  {
    id: "milliy-family-restaurant",
    name: "Milliy Family Restaurant",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "1279 Rickert Dr, Naperville, IL 60540",
    cuisine: "Uzbek / Central Asian",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 280,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7508,
    lng: -88.1690,
    description: "Family-style Uzbek and Central Asian halal cuisine in Naperville.",
  },
  {
    id: "daves-hot-chicken-naperville",
    name: "Dave's Hot Chicken",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "2736 Showplace Dr, Naperville, IL 60564",
    cuisine: "American / Nashville Hot Chicken",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 400,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7040,
    lng: -88.1590,
    description: "Chain-supplied halal chicken; store-level certification clarity can vary.",
  },
  {
    id: "sabri-nihari",
    name: "Sabri Nihari Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2502 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani / Nihari",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 500,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6918,
    description: "Zabiha halal Devon Ave spot known for slow-cooked nihari.",
  },
  {
    id: "khan-bbq",
    name: "Khan B.B.Q. Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2401 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani / BBQ",
    halalStatus: "zabiha",
    rating: 4.2,
    reviewCount: 450,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6905,
    description: "Zabiha halal Pakistani BBQ on the Devon Ave corridor.",
  },
  {
    id: "pita-inn",
    name: "Pita Inn",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "4710 Dempster St, Skokie, IL 60076",
    cuisine: "Middle Eastern / Mediterranean",
    halalStatus: "zabiha",
    rating: 4.6,
    reviewCount: 2500,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0392,
    lng: -87.7592,
    description: "Long-running Zabiha halal Middle Eastern favorite on Dempster St.",
  },
  {
    id: "halal-guys-wabash",
    name: "The Halal Guys",
    neighborhood: "The Loop",
    region: "Chicago",
    address: "172 N Wabash Ave, Chicago, IL 60601",
    cuisine: "Middle Eastern / Halal Cart",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 900,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8857,
    lng: -87.6266,
    description: "Loop location of the famous halal cart chain — chicken and gyro over rice.",
  },
  {
    id: "halal-guys-lasalle",
    name: "The Halal Guys",
    neighborhood: "The Loop",
    region: "Chicago",
    address: "100 N LaSalle St, Chicago, IL 60602",
    cuisine: "Middle Eastern / Halal Cart",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 700,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8837,
    lng: -87.6323,
    description: "Loop location of the famous halal cart chain, near LaSalle St.",
  },
  {
    id: "halal-guys-division",
    name: "The Halal Guys",
    neighborhood: "Near North Side",
    region: "Chicago",
    address: "49 W Division St, Chicago, IL 60610",
    cuisine: "Middle Eastern / Halal Cart",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 650,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9037,
    lng: -87.6298,
    description: "Near North Side location of the famous halal cart chain.",
  },
  {
    id: "habibis-chicken-falafel",
    name: "Habibi's Chicken & Falafel",
    neighborhood: "Oak Park",
    region: "West Suburbs",
    address: "421 N Harlem Ave, Oak Park, IL 60301",
    cuisine: "Middle Eastern / Falafel",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8969,
    lng: -87.8067,
    description: "Halal chicken and falafel spot serving Oak Park.",
  },
  {
    id: "taza-mediterranean",
    name: "Taza Mediterranean Cuisine",
    neighborhood: "The Loop",
    region: "Chicago",
    address: "176 N Franklin St #1822, Chicago, IL 60606",
    cuisine: "Mediterranean",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 320,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8850,
    lng: -87.6349,
    description: "Loop Mediterranean halal fare near Franklin St.",
  },
  {
    id: "nile-of-hyde-park",
    name: "The Nile of Hyde Park",
    neighborhood: "Hyde Park",
    region: "Chicago",
    address: "1162 E 55th St, Chicago, IL 60615",
    cuisine: "Middle Eastern / Egyptian",
    halalStatus: "select-items",
    rating: 4.1,
    reviewCount: 210,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7947,
    lng: -87.5924,
    description: "Egyptian-inspired Middle Eastern fare in Hyde Park; select menu items are halal.",
  },
  {
    id: "jerusalem-cafe-grill",
    name: "Jerusalem Cafe Grill Restaurant",
    neighborhood: "Oak Park",
    region: "West Suburbs",
    address: "1030 Lake St, Oak Park, IL 60301",
    cuisine: "Middle Eastern / Mediterranean",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 240,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8857,
    lng: -87.7900,
    description: "Middle Eastern grill in Oak Park; select menu items are halal.",
  },
  {
    id: "epic-burger-state-st",
    name: "Epic Burger",
    neighborhood: "South Loop",
    region: "Chicago",
    address: "517 S State St, Chicago, IL 60605",
    cuisine: "American / Burgers",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 900,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8760,
    lng: -87.6277,
    description: "Chicago burger chain; select proteins are halal-sourced at participating locations.",
  },
  {
    id: "epic-burger-pearson-st",
    name: "Epic Burger",
    neighborhood: "Streeterville",
    region: "Chicago",
    address: "40 E Pearson St, Chicago, IL 60611",
    cuisine: "American / Burgers",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 700,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8977,
    lng: -87.6247,
    description: "Streeterville location of the Chicago burger chain; select items are halal.",
  },
  {
    id: "epic-burger-north-ave",
    name: "Epic Burger",
    neighborhood: "Lincoln Park",
    region: "Chicago",
    address: "1000 W North Ave, Chicago, IL 60642",
    cuisine: "American / Burgers",
    halalStatus: "select-items",
    rating: 4.2,
    reviewCount: 600,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9108,
    lng: -87.6528,
    description: "Lincoln Park location of the Chicago burger chain; select items are halal.",
  },
  {
    id: "epic-burger-skokie",
    name: "Epic Burger",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "4999 Old Orchard Shop Center East Ring Rd, Skokie, IL 60077",
    cuisine: "American / Burgers",
    halalStatus: "select-items",
    rating: 4.1,
    reviewCount: 350,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0764,
    lng: -87.7625,
    description: "Old Orchard location of the Chicago burger chain; select items are halal.",
  },
  {
    id: "epic-burger-northbrook",
    name: "Epic Burger",
    neighborhood: "Northbrook",
    region: "North Suburbs",
    address: "1036 Willow Rd, Northbrook, IL 60062",
    cuisine: "American / Burgers",
    halalStatus: "select-items",
    rating: 4.1,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.1275,
    lng: -87.7970,
    description: "Northbrook location of the Chicago burger chain; select items are halal.",
  },
  {
    id: "seven-spices",
    name: "7 Spices",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "Indian / Indo-Chinese",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.7473,
    description: "Halal Hyderabadi and Indo-Chinese cuisine in Skokie.",
  },
  {
    id: "zad-by-pita-inn",
    name: "Zad by Pita Inn",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "Middle Eastern / Mediterranean",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 200,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.7460,
    description: "Sister concept to Pita Inn, serving halal Middle Eastern fare in Skokie.",
  },
  {
    id: "sizzle-skokie",
    name: "Sizzle",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "American / Burgers",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 180,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.7480,
    description: "Halal smash burgers, crispy chicken sandwiches, and boba tea in Skokie.",
  },
  {
    id: "browns-chicken-skokie",
    name: "Brown's Chicken",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "3949 Oakton St, Skokie, IL 60076",
    cuisine: "American / Fried Chicken",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0392,
    lng: -87.7530,
    description: "Chicago-area fried chicken chain location serving all-halal meat in Skokie.",
  },
  {
    id: "masala-magic",
    name: "Masala Magic Restaurant",
    neighborhood: "River North",
    region: "Chicago",
    address: "1011 N Orleans St, Chicago, IL 60610",
    cuisine: "Bangladeshi / Indian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 150,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9019,
    lng: -87.6373,
    description: "Halal Bangladeshi and Indian cuisine in River North.",
  },
  {
    id: "olive-mediterranean-grill",
    name: "Olive Mediterranean Grill",
    neighborhood: "Goose Island",
    region: "Chicago",
    address: "1001 W North Ave, Chicago, IL 60642",
    cuisine: "Mediterranean",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9108,
    lng: -87.6540,
    description: "Halal Mediterranean grill near Goose Island.",
  },
  {
    id: "the-charcoal-grill",
    name: "The Charcoal Grill",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "Schaumburg, IL",
    cuisine: "American / Pakistani Grill",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0333,
    lng: -88.0834,
    description: "Pickup-only halal charcoal-grilled burgers and rice bowls with South Asian flavors.",
  },
  {
    id: "bawarchi-biryanis",
    name: "Bawarchi Biryanis",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "Schaumburg, IL",
    cuisine: "Indian / Pakistani",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 400,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0333,
    lng: -88.0800,
    description: "Halal Indian and Pakistani biryani house in a Schaumburg strip mall.",
  },
  {
    id: "imli-schaumburg",
    name: "IMLI",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "1725 E Algonquin Rd, Schaumburg, IL 60173",
    cuisine: "Indian",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 350,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0459,
    lng: -88.0670,
    description: "Modern halal Indian dining room serving biryani, naan, and butter chicken.",
  },
  {
    id: "al-badia-tandoori-dallah",
    name: "Al Badia / Tandoori / Dallah",
    neighborhood: "Villa Park",
    region: "West Suburbs",
    address: "234 W Roosevelt Rd, Villa Park, IL 60181",
    cuisine: "Middle Eastern / Pakistani",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8734,
    lng: -87.9760,
    description: "Combined halal Middle Eastern and Pakistani menu on Roosevelt Rd in Villa Park.",
  },
  {
    id: "al-manakeesh",
    name: "Al Manakeesh",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "8401 S Harlem Ave, Bridgeview, IL 60455",
    cuisine: "Middle Eastern / Palestinian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 400,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7412,
    lng: -87.8070,
    description: "Wood-fired manakeesh and Palestinian halal fare in Bridgeview.",
  },
];

interface GooglePlaceEnrichment {
  placeId: string;
  matchedName: string | null;
  formattedAddress: string | null;
  lat: number | null;
  lng: number | null;
  rating: number | null;
  userRatingCount: number | null;
  googleMapsUri: string | null;
  websiteUri: string | null;
  openingHours: string[] | null;
  photos: { name: string; widthPx: number; heightPx: number }[];
}

const googlePlacesData = googlePlacesDataJson as Record<string, GooglePlaceEnrichment>;

function placePhotoUrl(photoName: string, width = 900): string {
  return `/api/place-photo?name=${encodeURIComponent(photoName)}&w=${width}`;
}

/**
 * Base seed data merged with verified Google Places data (ratings, review
 * counts, coordinates, formatted address, photos, hours) where a confident
 * match was found by scripts/enrich-places.mjs. Halal status is never
 * sourced from Google — that stays our own editorial call.
 */
export const restaurants: Restaurant[] = baseRestaurants.map((restaurant) => {
  const enrichment = googlePlacesData[restaurant.id];
  const cuisineCategory = categorizeCuisine(restaurant.cuisine);

  if (!enrichment) return { ...restaurant, cuisineCategory };

  return {
    ...restaurant,
    cuisineCategory,
    lat: enrichment.lat ?? restaurant.lat,
    lng: enrichment.lng ?? restaurant.lng,
    address: enrichment.formattedAddress ?? restaurant.address,
    rating: enrichment.rating ?? restaurant.rating,
    reviewCount: enrichment.userRatingCount ?? restaurant.reviewCount,
    image: enrichment.photos[0] ? placePhotoUrl(enrichment.photos[0].name) : restaurant.image,
    googleMapsUri: enrichment.googleMapsUri ?? undefined,
    websiteUri: enrichment.websiteUri ?? undefined,
    openingHours: enrichment.openingHours ?? undefined,
  };
});

export const CUISINE_CATEGORIES: string[] = Array.from(
  new Set(restaurants.map((r) => r.cuisineCategory)),
).sort();

export const REGIONS: {
  id: Region;
  label: string;
  center: [number, number];
  zoom: number;
}[] = [
  { id: "Chicago", label: "Chicago", center: [41.9200, -87.7000], zoom: 11 },
  { id: "North Suburbs", label: "North suburbs", center: [42.0500, -87.7300], zoom: 11 },
  { id: "Northwest Suburbs", label: "Northwest suburbs", center: [42.0500, -88.0100], zoom: 10.5 },
  { id: "West Suburbs", label: "West suburbs", center: [41.8300, -88.0800], zoom: 10.5 },
  { id: "Southwest Suburbs", label: "Southwest suburbs", center: [41.7400, -87.8100], zoom: 11 },
  { id: "South Suburbs", label: "South suburbs", center: [41.5900, -87.8200], zoom: 11 },
];

export const CHICAGOLAND_CENTER: [number, number] = [41.85, -87.82];
export const CHICAGOLAND_ZOOM = 9;
