import googlePlacesDataJson from "./google-places-data.json";

export type HalalStatus = "zabiha" | "halal" | "select-items";

export type Region =
  | "Chicago"
  | "North Suburbs"
  | "Northwest Suburbs"
  | "West Suburbs"
  | "Southwest Suburbs"
  | "South Suburbs";

export interface Restaurant {
  id: string;
  name: string;
  neighborhood: string;
  region: Region;
  address: string;
  cuisine: string;
  halalStatus: HalalStatus;
  rating: number;
  reviewCount: number;
  priceLevel: "$" | "$$" | "$$$";
  image: string;
  lat: number;
  lng: number;
  description: string;
  /** Present when verified against Google Places (see scripts/enrich-places.mjs). */
  googleMapsUri?: string;
  websiteUri?: string;
  openingHours?: string[];
}

/**
 * Seed dataset compiled from public halal-directory sources (Zabihah listings,
 * local halal-food roundups, restaurant sites) for the initial Chicagoland
 * launch map. Addresses/coordinates for the Devon Ave and Bridgeview clusters
 * are well corroborated; several suburban entries rest on a single directory
 * snapshot and should be re-verified (hours, certification, still open) by
 * an editorial/data pipeline before being treated as authoritative.
 */
const baseRestaurants: Restaurant[] = [
  {
    id: "karachi-chaat-house",
    name: "Karachi Chaat House",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2301 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani",
    halalStatus: "zabiha",
    rating: 4.6,
    reviewCount: 812,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6889,
    description: "Devon Ave institution serving 100% Zabiha bun kabab, biryani, and nihari late into the night.",
  },
  {
    id: "usmania-fine-dining",
    name: "Usmania Fine Dining",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2244 W Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani / Indian",
    halalStatus: "zabiha",
    rating: 4.4,
    reviewCount: 640,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6880,
    description: "Established South Asian dining room on Devon Ave known for karahi and Zabiha meats.",
  },
  {
    id: "spinzer-restaurant",
    name: "Spinzer Restaurant",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "Devon Ave near Western Ave, Chicago, IL",
    cuisine: "Pakistani Street Food",
    halalStatus: "zabiha",
    rating: 4.5,
    reviewCount: 410,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6903,
    description: "Zabiha halal Pakistani street food — chaat, biryani, and karahi — since 2008.",
  },
  {
    id: "ghareeb-nawaz",
    name: "Ghareeb Nawaz",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "Devon Ave, Chicago, IL 60659",
    cuisine: "Pakistani / Indian",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 980,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6870,
    description: "No-frills Devon Ave staple with 100+ menu items, open until 2am.",
  },
  {
    id: "new-naan-on-devon",
    name: "New Naan on Devon",
    neighborhood: "West Ridge",
    region: "Chicago",
    address: "2241 W Devon Ave, Chicago, IL 60659",
    cuisine: "Hyderabadi / Middle Eastern Grill",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9979,
    lng: -87.6878,
    description: "Hyderabadi biryani and Middle Eastern grill items on the Devon corridor.",
  },
  {
    id: "sultans-market",
    name: "Sultan's Market",
    neighborhood: "Wicker Park",
    region: "Chicago",
    address: "Milwaukee Ave & North Ave, Chicago, IL",
    cuisine: "Mediterranean / Middle Eastern",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 1200,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9100,
    lng: -87.6773,
    description: "Decades-old Wicker Park halal falafel and shawarma counter.",
  },
  {
    id: "semiramis",
    name: "Semiramis",
    neighborhood: "Lincoln Square",
    region: "Chicago",
    address: "Lincoln Ave, Chicago, IL",
    cuisine: "Middle Eastern Bakery / Deli",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 350,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.9686,
    lng: -87.6890,
    description: "Long-standing halal Middle Eastern bakery and deli known for shawarma and manakeesh.",
  },
  {
    id: "kabul-house",
    name: "Kabul House",
    neighborhood: "Evanston",
    region: "North Suburbs",
    address: "Davis St, Evanston, IL",
    cuisine: "Afghan",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 540,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0451,
    lng: -87.6877,
    description: "Well-regarded Afghan restaurant known for mantu and kabobs.",
  },
  {
    id: "jarasa-kabob",
    name: "Jarasa Kabob",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Oakton St area, Skokie, IL",
    cuisine: "Middle Eastern / Mediterranean",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 300,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0324,
    lng: -87.7412,
    description: "Popular kabob and shawarma spot serving Skokie, Evanston, and Lincolnwood.",
  },
  {
    id: "sheikhs-n-burgers",
    name: "Sheikhs N Burgers",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "American / Burgers",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 190,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.7473,
    description: "Halal burger concept popular with the North Shore Muslim community.",
  },
  {
    id: "afghan-kabob-skokie",
    name: "Afghan Kabob",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Dempster St, Skokie, IL",
    cuisine: "Afghan",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0392,
    lng: -87.7515,
    description: "Dempster St Afghan spot known for mantu dumplings and traditional kabobs.",
  },
  {
    id: "byrds-hot-chicken",
    name: "Byrd's Hot Chicken",
    neighborhood: "Skokie",
    region: "North Suburbs",
    address: "Skokie, IL",
    cuisine: "American / Fried Chicken",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 150,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0389,
    lng: -87.7448,
    description: "Nashville-style hot chicken with a halal Skokie location.",
  },
  {
    id: "barakat-restaurant",
    name: "Barakat Restaurant",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "Schaumburg, IL",
    cuisine: "Middle Eastern / Palestinian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 410,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0333,
    lng: -88.0834,
    description: "Regional halal Mediterranean/Palestinian restaurant with multiple NW suburb locations.",
  },
  {
    id: "ali-baba-kabab",
    name: "Ali Baba Kabab",
    neighborhood: "Schaumburg",
    region: "Northwest Suburbs",
    address: "Roselle Rd, Schaumburg, IL",
    cuisine: "Middle Eastern",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1633945274309-2c3b3d9be1e5?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0459,
    lng: -88.0784,
    description: "Roselle Rd kabob and grill spot popular in Schaumburg's halal food scene.",
  },
  {
    id: "curry-naanstop",
    name: "Curry NaanStop",
    neighborhood: "Mount Prospect",
    region: "Northwest Suburbs",
    address: "338 E Rand Rd, Mount Prospect, IL 60004",
    cuisine: "Indian / Pakistani",
    halalStatus: "halal",
    rating: 4.8,
    reviewCount: 520,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0928,
    lng: -87.9364,
    description: "Halal-certified Indian restaurant on the Rand Rd corridor.",
  },
  {
    id: "uyghur-lagman-house",
    name: "Uyghur Lagman House",
    neighborhood: "Arlington Heights",
    region: "Northwest Suburbs",
    address: "Arlington Heights, IL",
    cuisine: "Uyghur / Central Asian",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 180,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0884,
    lng: -87.9806,
    description: "Rare Uyghur hand-pulled noodle house serving halal Central Asian cuisine.",
  },
  {
    id: "mazmez-grill",
    name: "MazMez Middle Eastern Grill",
    neighborhood: "Elk Grove Village",
    region: "Northwest Suburbs",
    address: "Elk Grove Village, IL",
    cuisine: "Middle Eastern",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 140,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0034,
    lng: -87.9773,
    description: "Middle Eastern grill offering shawarma and kabobs in Elk Grove Village.",
  },
  {
    id: "a-thousand-tales",
    name: "A Thousand Tales",
    neighborhood: "Des Plaines",
    region: "Northwest Suburbs",
    address: "Des Plaines, IL",
    cuisine: "Middle Eastern Bakery / Cafe",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 210,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 42.0334,
    lng: -87.8834,
    description: "Middle Eastern bakery-cafe concept with locations across the NW suburbs.",
  },
  {
    id: "jk-kabab",
    name: "JK Kabab",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "572 Weston Ridge Dr, Naperville, IL",
    cuisine: "Indian / Pakistani",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 330,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7508,
    lng: -88.1535,
    description: "Naperville halal grill known for kabobs and Desi-style curries.",
  },
  {
    id: "habibi-shawarma",
    name: "Habibi Shawarma",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "Naperville, IL",
    cuisine: "Middle Eastern / Shawarma",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 290,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7858,
    lng: -88.1470,
    description: "Popular Naperville shawarma and falafel counter.",
  },
  {
    id: "halal-express-villa-park",
    name: "Halal Express",
    neighborhood: "Villa Park",
    region: "West Suburbs",
    address: "17W731 Roosevelt Rd, Villa Park, IL",
    cuisine: "American / Halal Fast Food",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 175,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8734,
    lng: -87.9989,
    description: "Roosevelt Rd quick-service halal spot serving gyro and chicken-over-rice plates.",
  },
  {
    id: "biryani-pointe",
    name: "Biryani Pointe",
    neighborhood: "Lombard",
    region: "West Suburbs",
    address: "40 W Roosevelt Rd, Lombard, IL",
    cuisine: "Pakistani / Indian",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 240,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.8595,
    lng: -88.0084,
    description: "Biryani and kabob restaurant on the Roosevelt Rd corridor in Lombard.",
  },
  {
    id: "tapri",
    name: "Tapri",
    neighborhood: "Naperville",
    region: "West Suburbs",
    address: "Naperville, IL",
    cuisine: "Indian Street Food / Chai",
    halalStatus: "select-items",
    rating: 4.3,
    reviewCount: 160,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7796,
    lng: -88.1616,
    description: "Indian street-food and chai cafe; select menu items are prepared halal.",
  },
  {
    id: "al-bawadi-grill",
    name: "Al Bawadi Grill",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "7216 W 87th St, Bridgeview, IL 60455",
    cuisine: "Palestinian / Middle Eastern",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 1500,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7361,
    lng: -87.8103,
    description: "Fully halal Palestinian restaurant famous for mansaf and musakhan.",
  },
  {
    id: "nariman-restaurant",
    name: "Nariman Restaurant",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "8312 S Harlem Ave, Bridgeview, IL",
    cuisine: "Middle Eastern",
    halalStatus: "zabiha",
    rating: 4.3,
    reviewCount: 280,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7412,
    lng: -87.8067,
    description: "Harlem Ave Middle Eastern restaurant serving Zabiha halal fare.",
  },
  {
    id: "krave-restaurant",
    name: "Krave Restaurant",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "Bridgeview, IL",
    cuisine: "American / Middle Eastern Fusion",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 340,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7500,
    lng: -87.8103,
    description: "100% halal menu; open 24 hours Fridays and Saturdays, a popular late-night spot.",
  },
  {
    id: "mdakhan",
    name: "M'daKhan",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "Bridgeview, IL",
    cuisine: "Middle Eastern / Smoked BBQ",
    halalStatus: "halal",
    rating: 4.4,
    reviewCount: 210,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1633945274309-2c3b3d9be1e5?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7450,
    lng: -87.8050,
    description: "Smoked halal Middle Eastern BBQ concept in Bridgeview.",
  },
  {
    id: "holy-buckets",
    name: "Holy Buckets Halal Chicken & Pizza",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "7331 W 87th St, Bridgeview, IL",
    cuisine: "American / Fried Chicken",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 260,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7360,
    lng: -87.8129,
    description: "Halal fried chicken and pizza serving Bridgeview, Oak Lawn, and Justice.",
  },
  {
    id: "alasala",
    name: "Alasala",
    neighborhood: "Bridgeview",
    region: "Southwest Suburbs",
    address: "Bridgeview, IL",
    cuisine: "Mediterranean / Palestinian",
    halalStatus: "halal",
    rating: 4.3,
    reviewCount: 190,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.7480,
    lng: -87.8090,
    description: "Muslim-owned Mediterranean/Palestinian restaurant in Bridgeview.",
  },
  {
    id: "semsem-mediterranean",
    name: "SemSem Mediterranean",
    neighborhood: "Orland Park",
    region: "South Suburbs",
    address: "Orland Park, IL",
    cuisine: "Mediterranean",
    halalStatus: "halal",
    rating: 4.5,
    reviewCount: 300,
    priceLevel: "$$",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.6303,
    lng: -87.8531,
    description: "Orland Park Mediterranean grill offering halal shawarma, platters, and catering.",
  },
  {
    id: "brooklyn-halal",
    name: "Brooklyn Halal Grilled Chicken & Pizza",
    neighborhood: "Tinley Park",
    region: "South Suburbs",
    address: "Tinley Park, IL",
    cuisine: "American / Fried Chicken & Pizza",
    halalStatus: "halal",
    rating: 4.2,
    reviewCount: 220,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.5735,
    lng: -87.7929,
    description: "Halal fried chicken and pizza chain with a South Suburbs footprint.",
  },
  {
    id: "nazs-halal-food",
    name: "Naz's Halal Food",
    neighborhood: "Tinley Park",
    region: "South Suburbs",
    address: "Tinley Park, IL",
    cuisine: "Halal Grill",
    halalStatus: "halal",
    rating: 4.6,
    reviewCount: 180,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1626500881415-06751e26ef0e?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.5764,
    lng: -87.7847,
    description: "Top-rated Tinley Park halal grill in local roundups.",
  },
  {
    id: "hakuna-matata",
    name: "Hakuna Matata",
    neighborhood: "Orland Park",
    region: "South Suburbs",
    address: "Orland Park, IL",
    cuisine: "African / Halal Grill",
    halalStatus: "halal",
    rating: 4.1,
    reviewCount: 130,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.6112,
    lng: -87.8536,
    description: "African-influenced halal grill serving the Orland Park / Tinley Park area.",
  },
  {
    id: "wow-halal-grill",
    name: "Wow Halal Grill & Pizza",
    neighborhood: "Tinley Park",
    region: "South Suburbs",
    address: "Tinley Park, IL",
    cuisine: "American / Halal Fast Food",
    halalStatus: "halal",
    rating: 4.0,
    reviewCount: 150,
    priceLevel: "$",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&fm=jpg&q=80&w=900",
    lat: 41.5798,
    lng: -87.7900,
    description: "Casual halal grill-and-pizza spot serving the Tinley Park area.",
  },
];

interface GooglePlaceEnrichment {
  placeId: string;
  matchedName: string | null;
  formattedAddress: string | null;
  lat: number | null;
  lng: number | null;
  rating: number | null;
  userRatingCount: number | null;
  googleMapsUri: string | null;
  websiteUri: string | null;
  openingHours: string[] | null;
  photos: { name: string; widthPx: number; heightPx: number }[];
}

const googlePlacesData = googlePlacesDataJson as Record<string, GooglePlaceEnrichment>;

function placePhotoUrl(photoName: string, width = 900): string {
  return `/api/place-photo?name=${encodeURIComponent(photoName)}&w=${width}`;
}

/**
 * Base seed data merged with verified Google Places data (ratings, review
 * counts, coordinates, formatted address, photos, hours) where a confident
 * match was found by scripts/enrich-places.mjs. Halal status is never
 * sourced from Google — that stays our own editorial call.
 */
export const restaurants: Restaurant[] = baseRestaurants.map((restaurant) => {
  const enrichment = googlePlacesData[restaurant.id];
  if (!enrichment) return restaurant;

  return {
    ...restaurant,
    lat: enrichment.lat ?? restaurant.lat,
    lng: enrichment.lng ?? restaurant.lng,
    address: enrichment.formattedAddress ?? restaurant.address,
    rating: enrichment.rating ?? restaurant.rating,
    reviewCount: enrichment.userRatingCount ?? restaurant.reviewCount,
    image: enrichment.photos[0] ? placePhotoUrl(enrichment.photos[0].name) : restaurant.image,
    googleMapsUri: enrichment.googleMapsUri ?? undefined,
    websiteUri: enrichment.websiteUri ?? undefined,
    openingHours: enrichment.openingHours ?? undefined,
  };
});

export const REGIONS: {
  id: Region;
  label: string;
  center: [number, number];
  zoom: number;
}[] = [
  { id: "Chicago", label: "Chicago", center: [41.9200, -87.7000], zoom: 11 },
  { id: "North Suburbs", label: "North suburbs", center: [42.0500, -87.7300], zoom: 11 },
  { id: "Northwest Suburbs", label: "Northwest suburbs", center: [42.0500, -88.0100], zoom: 10.5 },
  { id: "West Suburbs", label: "West suburbs", center: [41.8300, -88.0800], zoom: 10.5 },
  { id: "Southwest Suburbs", label: "Southwest suburbs", center: [41.7400, -87.8100], zoom: 11 },
  { id: "South Suburbs", label: "South suburbs", center: [41.5900, -87.8200], zoom: 11 },
];

export const CHICAGOLAND_CENTER: [number, number] = [41.85, -87.82];
export const CHICAGOLAND_ZOOM = 9;
